spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cramind
    username: root
    password: keypass
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: update


jwt:
  issuer: project.doctalk@gmail.com
  secret: "jfsgkhdsjkweoiruwqejkrfbhnsadkjlfghbwerqewrsdfgdsfagbdf"
  access-expiration: 3600
  refresh-expiration: 8640

github:
  api-url: https://api.github.com
  token: ${PAT_TOKEN}

server:
  port: 8080
  address: 0.0.0.0