spring:
  datasource:
    url: jdbc:mysql://localhost:3306/veri
    username: root
    password: keypass
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB